runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:pGgKt/uwwEAZU2aNy/Dn96BM1wdSmb20wE0uPaozmsA=


  ## To use Stackdriver logging in your Laravel application, copy
  ## "app/Logging/CreateStackdriverLogger.php" and "config/logging.php"
  ## into your Laravel application. Then uncomment the following line:
  # LOG_CHANNEL: stackdriver
